#!/usr/bin/env python3
import html
import os
import sys
from urllib.parse import parse_qs

method = os.environ.get("REQUEST_METHOD", "")
query_string = os.environ.get("QUERY_STRING", "")
content_length = int(os.environ.get("CONTENT_LENGTH", "0") or "0")
content_type = os.environ.get("CONTENT_TYPE", "")
request_uri = os.environ.get("REQUEST_URI", "")
body = sys.stdin.read(content_length) if content_length > 0 else ""
query = parse_qs(query_string, keep_blank_values=True)

print("Content-Type: text/html; charset=utf-8")
print()
print("<!doctype html>")
print("<html lang='en'>")
print("  <head>")
print("    <meta charset='utf-8'>")
print("    <meta name='viewport' content='width=device-width, initial-scale=1'>")
print("    <title>CGI echo</title>")
print("    <style>")
print("      body { font-family: Arial, Helvetica, sans-serif; background:#081018; color:#eef6fb; margin:0; padding:32px; }")
print("      .card { max-width: 900px; margin: 0 auto; padding: 24px; border-radius: 20px; background: rgba(255,255,255,0.04); border: 1px solid rgba(255,255,255,0.1); }")
print("      pre { white-space: pre-wrap; word-break: break-word; padding: 16px; border-radius: 16px; background: rgba(0,0,0,0.22); }")
print("      h1 { margin-top: 0; }")
print("      .meta { color: #9fb2c0; }")
print("    </style>")
print("  </head>")
print("  <body>")
print("    <div class='card'>")
print("      <h1>CGI echo</h1>")
print("      <p class='meta'>This page is generated by <code>website/cgi-bin/echo.py</code>.</p>")
print("      <h2>Request summary</h2>")
print(f"      <pre>method: {html.escape(method)}\nrequest_uri: {html.escape(request_uri)}\nquery_string: {html.escape(query_string)}\ncontent_type: {html.escape(content_type)}\ncontent_length: {content_length}\n\nbody:\n{html.escape(body)}</pre>")
print("      <h2>Parsed query</h2>")
print(f"      <pre>{html.escape(repr(query))}</pre>")
print("    </div>")
print("  </body>")
print("</html>")#!/usr/bin/env python3
import html
import os
import sys
from urllib.parse import parse_qs

method = os.environ.get("REQUEST_METHOD", "")
query_string = os.environ.get("QUERY_STRING", "")
content_length = int(os.environ.get("CONTENT_LENGTH", "0") or "0")
content_type = os.environ.get("CONTENT_TYPE", "")
request_uri = os.environ.get("REQUEST_URI", "")
body = sys.stdin.read(content_length) if content_length > 0 else ""
query = parse_qs(query_string, keep_blank_values=True)

print("Content-Type: text/html; charset=utf-8")
print()
print("<!doctype html>")
print("<html lang='en'>")
print("  <head>")
print("    <meta charset='utf-8'>")
print("    <meta name='viewport' content='width=device-width, initial-scale=1'>")
print("    <title>CGI echo</title>")
print("    <style>")
print("      body { font-family: Arial, Helvetica, sans-serif; background:#081018; color:#eef6fb; margin:0; padding:32px; }")
print("      .card { max-width: 900px; margin: 0 auto; padding: 24px; border-radius: 20px; background: rgba(255,255,255,0.04); border: 1px solid rgba(255,255,255,0.1); }")
print("      pre { white-space: pre-wrap; word-break: break-word; padding: 16px; border-radius: 16px; background: rgba(0,0,0,0.22); }")
print("      h1 { margin-top: 0; }")
print("      .meta { color: #9fb2c0; }")
print("    </style>")
print("  </head>")
print("  <body>")
print("    <div class='card'>")
print("      <h1>CGI echo</h1>")
print("      <p class='meta'>This page is generated by <code>docs/fusion_web/cgi-bin/echo.py</code>.</p>")
print("      <h2>Request summary</h2>")
print(f"      <pre>method: {html.escape(method)}\nrequest_uri: {html.escape(request_uri)}\nquery_string: {html.escape(query_string)}\ncontent_type: {html.escape(content_type)}\ncontent_length: {content_length}\n\nbody:\n{html.escape(body)}</pre>")
print("      <h2>Parsed query</h2>")
print(f"      <pre>{html.escape(repr(query))}</pre>")
print("    </div>")
print("  </body>")
print("</html>")
