server {
    listen 8000;
    host 127.0.0.1;
    server_name localhost;
    root docs/fusion_web/;
    index index.html;
    client_max_body_size 1000000;

    location / {
        allow_methods GET POST;
        autoindex on;
    }

    location /upload {
        allow_methods POST;
        root docs/fusion_web/;
    }
}

server {
    listen 8001;
    host 127.0.0.1;
    server_name test.local;
    root docs/fusion_web/;
    index index.html;
    client_max_body_size 500000;

    location / {
        allow_methods GET;
        autoindex off;
    }
}