server {
    listen      8080;
    server_name localhost;

    root        websites;
    index       index.html;

    client_max_body_size 3000000;

    error_page 400 error_pages/400.html;
    error_page 403 error_pages/403.html;
    error_page 404 error_pages/404.html;
    error_page 405 error_pages/405.html;
    error_page 413 error_pages/413.html;
    error_page 500 error_pages/500.html;
    error_page 502 error_pages/502.html;

    location / {
        allow_methods GET POST DELETE;
        autoindex     off;
        index         index.html;
    }

    location /pages {
        allow_methods GET POST;
        autoindex     off;
        root          websites/pages;
    }

    location /assets {
        allow_methods GET;
        autoindex     off;
    }

    location /error_pages {
        allow_methods GET;
        autoindex     off;
    }

    location /uploads {
        allow_methods GET POST DELETE;
        autoindex     on;
        upload_store  websites/uploads;
    }

    location /cgi-bin {
        allow_methods GET POST;
        root          websites/cgi-bin;
        index         echo.py;
        cgi_ext       .py;
        cgi_path      /usr/bin/python3;
    }

    location /home {
        allow_methods GET;
        return        /;
    }

    location /about {
        allow_methods GET;
        return        /pages/about.html;
    }

    location /services {
        allow_methods GET;
        return        /pages/services.html;
    }

    location /contact {
        allow_methods GET;
        return        /pages/contact.html;
    }

    location /login {
        allow_methods GET POST;
        return        /pages/login.html;
    }

    location /signup {
        allow_methods GET POST;
        return        /pages/signup.html;
    }

    # location /dashboard {
    #     allow_methods GET;
    #     return        /pages/dashboard.html;
    # }
}
